In [2]:
import numpy as np

In [3]:
def get_distance_mask(L):
    m = np.zeros((3, L, L))

    for i in range(L):
        for j in range(L):
            for k in range(3):
                if abs(i - j) > 0:
                    m[k, i, j] = 1 / abs(i - j) ** (k + 1)
    return m

get_distance_mask(3)

array([[[0.   , 1.   , 0.5  ],
        [1.   , 0.   , 1.   ],
        [0.5  , 1.   , 0.   ]],

       [[0.   , 1.   , 0.25 ],
        [1.   , 0.   , 1.   ],
        [0.25 , 1.   , 0.   ]],

       [[0.   , 1.   , 0.125],
        [1.   , 0.   , 1.   ],
        [0.125, 1.   , 0.   ]]])

In [4]:
def tmp():
    print(1)
    for _ in range(1):
        exit()
    print(2)

tmp()

1
2


: 

In [6]:
def generate_src_mask(L1, L2, k):
    mask = np.ones((k, L2), dtype="int8")
    for i in range(k):
        mask[i, L1 + i + 1 - k :] = 0
    return mask

generate_src_mask(5, 6, 3)

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0]], dtype=int8)

In [7]:
for i in range(5):
    ! kaggle competitions submit -c stanford-covid-vaccine -f best_weights_subs/submission_fold{i}.csv -m "Message"

100%|██████████████████████████████████████| 49.6M/49.6M [00:13<00:00, 3.73MB/s]
100%|██████████████████████████████████████| 49.6M/49.6M [00:09<00:00, 5.72MB/s]ion
100%|██████████████████████████████████████| 49.7M/49.7M [00:08<00:00, 5.89MB/s]ion
100%|██████████████████████████████████████| 49.7M/49.7M [00:10<00:00, 4.99MB/s]ion
100%|██████████████████████████████████████| 49.6M/49.6M [00:07<00:00, 6.62MB/s]ion
Successfully submitted to OpenVaccine: COVID-19 mRNA Vaccine Degradation Prediction

In [13]:
import numpy as np
a = np.load('data/train_test_bpps/id_00073f8be_bpp.npy')

In [14]:
a.shape

(12, 107, 107)

In [15]:
b = np.pad(
    a,
    ([0, 0], [0, 130 - a.shape[1]], [0, 130 - a.shape[2]]),
    constant_values=0,
)

In [16]:
b.shape

(12, 130, 130)

In [19]:
a[0][:10, :10]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00639796],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00150547, 0.        , 0.00523535],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00176559, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00517606],
       [0.        , 0.00150547, 0.0017655

In [46]:
import os
import pandas as pd

json_path = os.path.join("data", "train.json")
train = pd.read_json(json_path, lines=True)
json_path = os.path.join("data", "test.json")
test = pd.read_json(json_path, lines=True)
data = pd.concat([train, test], ignore_index=True)

In [47]:
data

index            id                                           sequence  \
0         0  id_001f94081  GGAAAAGCUCUAAUAACAGGAGACUAGGACUACGUAUUUCUAGGUA...   
1         1  id_0049f53ba  GGAAAAAGCGCGCGCGGUUAGCGCGCGCUUUUGCGCGCGCUGUACC...   
2         2  id_006f36f57  GGAAAGUGCUCAGAUAAGCUAAGCUCGAAUAGCAAUCGAAUAGAAU...   
3         3  id_0082d463b  GGAAAAGCGCGCGCGCGCGCGCGAAAAAGCGCGCGCGCGCGCGCGC...   
4         4  id_0087940f4  GGAAAAUAUAUAAUAUAUUAUAUAAAUAUAUUAUAGAAGUAUAAUA...   
...     ...           ...                                                ...   
6029   3629  id_ff691b7e5  GGAAACUAGCCAUGGGCAGGUUGAAGGUUGGGUGACACUAACUGGA...   
6030   3630  id_ff9bf3581  GGAAAUAGCGCCAUAGCCGAUUAUUAUAGGCAAUUUUAGCGAUUUA...   
6031   3631  id_ffc8f96a8  GGAAAGAUGUUCUGAUGAACAUCGGCUGUUCUAGCUUUCAUCUAUC...   
6032   3632  id_ffd7e8cc1  GGAAACCGUUAACCUGCAUCUUCAUGUUAUCGCUUGCGACAGCAAC...   
6033   3633  id_ffda94f24  GGAAAAACCAAUUGCUAUUAAAGGUUCCUUUGUUCGCUAAGUCCAA...   

                                              structure  \
0     .....((((((.......)))).)).((.....((..((((((......   
1     .....(((((((((((((((((((((((....)))))))))).)))...   
2     .....((((.((.....((((.(((.....)))..((((......)...   
3     ......((((((((((((((((......))))))))))))))))((...   
4     .....(((((((.((((((((((((.(((((((((....)))))))...   
...                                                 ...   
6029  ........((((((((..((((...((((((......))))))......   
6030  .......(((((...(((..........))).......(((........   
6031  .....(((((((....)))))))(((.(((((((((((((((((((...   
6032  ...............................((((((............   
6033  .......(((..((((....(((((.(((((((...((..(((((....   

                                    predicted_loop_type  signal_to_noise  \
0     EEEEESSSSSSHHHHHHHSSSSBSSXSSIIIIISSIISSSSSSHHH...            6.894   
1     EEEEESSSSSSSSSSSSSSSSSSSSSSSHHHHSSSSSSSSSSBSSS...            0.193   
2     EEEEESSSSISSIIIIISSSSMSSSHHHHHSSSMMSSSSHHHHHHS...            8.800   
3     EEEEEESSSSSSSSSSSSSSSSHHHHHHSSSSSSSSSSSSSSSSSS...            0.104   
4     EEEEESSSSSSSBSSSSSSSSSSSSBSSSSSSSSSHHHHSSSSSSS...            0.423   
...                                                 ...              ...   
6029  EEEEEEEESSSSSSSSMMSSSSIIISSSSSSHHHHHHSSSSSSIII...              NaN   
6030  EEEEEEESSSSSMMMSSSHHHHHHHHHHSSSMMMMMMMSSSHHHHH...              NaN   
6031  EEEEESSSSSSSHHHHSSSSSSSSSSBSSSSSSSSSSSSSSSSSSS...              NaN   
6032  EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSIIIIIIIII...              NaN   
6033  EEEEEEESSSIISSSSIIIISSSSSBSSSSSSSIIISSIISSSSSH...              NaN   

      SN_filter  seq_length  seq_scored  \
0           1.0         107          68   
1           0.0         107          68   
2           1.0         107          68   
3           0.0         107          68   
4           0.0         107          68   
...         ...         ...         ...   
6029        NaN         130          91   
6030        NaN         130          91   
6031        NaN         130          91   
6032        NaN         130          91   
6033        NaN         130          91   

                                       reactivity_error  \
0     [0.1359, 0.20700000000000002, 0.1633, 0.1452, ...   
1     [2.8272, 2.8272, 2.8272, 4.7343, 2.5676, 2.567...   
2     [0.0931, 0.13290000000000002, 0.11280000000000...   
3     [3.5229, 6.0748, 3.0374, 3.0374, 3.0374, 3.037...   
4     [1.665, 2.1728, 2.0041, 1.2405, 0.620200000000...   
...                                                 ...   
6029                                                NaN   
6030                                                NaN   
6031                                                NaN   
6032                                                NaN   
6033                                                NaN   

                                      deg_error_Mg_pH10  \
0     [0.26130000000000003, 0.38420000000000004, 0.1...   
1     [73705.3985, 73705.3985, 73705.3985, 73705.398...   
2     [0.1365, 0.223

In [25]:
np.asarray([a, a, a, a]).shape

(4, 3)

In [28]:
def generate_src_mask(L1, L2, k):
    mask = np.ones((k, L2), dtype="int8")
    for i in range(k):
        mask[i, L1 + i + 1 - k :] = 0
    return mask

generate_src_mask(10, 15, 5)

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], dtype=int8)

In [29]:
np.arange(300)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [39]:
np.random.uniform()

0.8596986977206711

In [ ]:
a = 